name: 'Deploy To Pterodactyl'
description: 'Deploy files to a Pterodactyl server'
inputs:
  source:
    description: 'The source file/folder to deploy'
    required: true
  target:
    description: 'The destination folder to deploy to'
    required: false
  panel-url:
    description: 'The API endpoint of the Pterodactyl server e.g. "https://pterodactyl.file.properties/'
    required: true
  server-id:
    description: 'The ID of the Pterodactyl server'
    required: true
  api-key:
    description: 'The API key of the Pterodactyl server'
    required: true
  restart:
    description: 'Whether to restart the server after deploying the plugin'
    required: false
    default: false
  force-restart:
    description: 'Force kill the server if it is running for faster restart'
    required: false
    default: false

runs:
  using: 'node16'
  main: 'dist/index.js'
